import type { Metadata } from "next";
import { Lato, Maven_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const mavenPro = Maven_Pro({
  subsets: ["latin"],
  variable: "--font-maven",
  weight: ["400", "600", "700"],
});

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["400", "700"],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mavenPro.variable} ${lato.variable} antialiased`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
